---
configure_terminal: false
configure_osx: true
configure_dotfiles: true

configure_dock: true
dockitems_remove:
  - Launchpad
  - Safari
  - Mail
  - Maps
  - Photos
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - FaceTime
  - Messages
  - "App Store"
  - Freeform
  - Keynote
  - Numbers
  - Pages

dockitems_persist:
  - name: "System Settings"
    path: "/Applications/System Settings.app"
    pos: 1
  - name: "Ghostty"
    path: "~/Applications/Ghostty.app"
    pos: 2

dotfiles_repo: https://github.com/nqui/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.config/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .osx
  - .vimrc
  - .config/pip/pip.conf
  - .nanorc
  - .gitconfig
  - .config/iterm2/iterm-profiles.json
  - "Library/Application Support/Rectangle/RectangleConfig.json"

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - httpie
  - iperf
  - ssh-copy-id
  - openssl
  - wget
  - zsh-history-substring-search
  - zsh-autosuggestions
  - nano
  - nanorc
  - zsh
  - powerlevel10k
  - go
  - tree
  - jq
  - mise

homebrew_cask_apps:
  - docker
  - 1password
  - discord
  - goland
  - pycharm
  - datagrip
  - rider
  - adguard
  - brave
  - rectangle
  - flux
  - spotify
  - vlc
  - balenaetcher
  - keka
  - protonvpn
